//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [DisplayName("Mã Số")]
        public int Id { get; set; }
        [DisplayName("Tên Đăng Nhập")]
        public string Username { get; set; }
        [DisplayName("Mật Khẩu")]
        public string Password { get; set; }
        [DisplayName("Họ Và Tên")]
        public string Name { get; set; }
    }
}
